### ISSUE TITLE
A problem with dynamically generated Python scripts 

### ISSUE THREAD

**Issue by 1605200517** [exoscale/cs#73]
Hi, is this a cs or ansible problem? 

https://stackoverflow.com/questions/52740831/debugging-ansible-trace-for-possible-bug-in-python-cloud-stack-module

How to reproduce (before docker build, change `cloudstack.ini.default` to `cloudstack.ini` with your Cloud Stack credentials and your API URL):
```
git clone https://gitlab.cc-asp.fraunhofer.de/peter.muryshkin/ansible-beginner.git
cd ansible-beginner
docker build -f Dockerfile.ubuntu16.04LTS -t foo .
```

Relevant Docker build log output regarding the question whether the SSH key is there (Dockerfile: line 8. `ls -alh ~/.ssh/`). if it is not there, Ansbile throws an error that this file is not available.
```
drwxrwxr-x 2 root root 4.0K Oct 10 12:54 .
drwx------ 1 root root 4.0K Oct 11 10:52 ..
-rw-r--r-- 1 root root 1.8K Oct 10 12:54 id_rsa.pub

```

Then, to reproduce the actual error, 

`docker run -it foo bash -c 'ansible-playbook -C main.yml -vvv'`

Error (locally, in other setup you need to check that the CloudStack API is available):

```
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 267, in <module>
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 258, in main
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 133, in register_ssh_key
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 211, in get_ssh_key
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 227, in _get_ssh_fingerprint
  File "/usr/local/lib/python2.7/dist-packages/sshpubkeys/keys.py", line 157, in hash_md5
    fp_plain = hashlib.md5(self._decoded_key).hexdigest()
TypeError: md5() argument 1 must be string or buffer, not None

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 267, in <module>\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 258, in main\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 133, in register_ssh_key\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 211, in get_ssh_key\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 227, in _get_ssh_fingerprint\n  File \"/usr/local/lib/python2.7/dist-packages/sshpubkeys/keys.py\", line 157, in hash_md5\n    fp_plain = hashlib.md5(self._decoded_key).hexdigest()\nTypeError: md5() argument 1 must be string or buffer, not None\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
	to retry, use: --limit @/work/ansible-beginner/main.retry

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1   
```

After this execution, if you would retain the test system (in the example above, the container gets thrown away), the temporary Python scripts seem to be cleaned up. How to retain them? For example, to check for the script contents `AnsiballZ_cs_sshkeypair.py`.

How does Ansible [require key specification](https://docs.ansible.com/ansible/2.5/modules/cs_sshkeypair_module.html#examples)?

```
# register your existing local public key:
- cs_sshkeypair:
    name: linus@example.com
    public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  delegate_to: localhost
```

How is it specified [in this setup](https://gitlab.cc-asp.fraunhofer.de/peter.muryshkin/ansible-beginner/blob/master/infrastructure/tasks/vm.yml)?
```

- cs_sshkeypair:
    name: my_sshkey
    public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  delegate_to: localhost


```

**Comment by greut** [comment]
I'd double check the key definition with the ansible documentation.

https://github.com/ansible/ansible/blob/a8d4bf86421d151d8df7132e8e87d04b6662f45a/lib/ansible/modules/cloud/cloudstack/cs_sshkeypair.py#L225

**Comment by 1605200517** [comment]
Greut - please give more details what is to doublecheck and which documentation part

**Comment by greut** [comment]
What is missing from the SO question is the ansible definition you're using.

https://docs.ansible.com/ansible/2.5/modules/cs_sshkeypair_module.html#examples

**Comment by greut** [comment]
I'd check that this file exists.

```yaml
public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
```

**Comment by 1605200517** [comment]
@greut in the line 8 of the Dockerfile, this is printed out:

`ls -alh ~/.ssh/`

I have added instructiion how to reproduce the error above to the body of the issue.

How to reproduce:
```
git clone https://gitlab.cc-asp.fraunhofer.de/peter.muryshkin/ansible-beginner.git
cd ansible-beginner
docker build -f Dockerfile.ubuntu16.04LTS -t foo .
```

Relevant Docker build log output regarding whether the SSH key is there; if it is not there, Ansbile throws an error that this file is not available.
```
drwxrwxr-x 2 root root 4.0K Oct 10 12:54 .
drwx------ 1 root root 4.0K Oct 11 10:52 ..
-rw-r--r-- 1 root root 1.8K Oct 10 12:54 id_rsa.pub

```

Then, to reproduce the actual error, 

`docker run -it foo bash -c 'ansible-playbook -C main.yml -vvv'`

Error (locally, in other setup you need to check that the CloudStack API is available):

```
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 267, in <module>
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 258, in main
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 133, in register_ssh_key
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 211, in get_ssh_key
  File "/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py", line 227, in _get_ssh_fingerprint
  File "/usr/local/lib/python2.7/dist-packages/sshpubkeys/keys.py", line 157, in hash_md5
    fp_plain = hashlib.md5(self._decoded_key).hexdigest()
TypeError: md5() argument 1 must be string or buffer, not None

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1539255360.27-44970784416337/AnsiballZ_cs_sshkeypair.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 267, in <module>\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 258, in main\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 133, in register_ssh_key\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 211, in get_ssh_key\n  File \"/tmp/ansible_cs_sshkeypair_payload_7Q2J_c/__main__.py\", line 227, in _get_ssh_fingerprint\n  File \"/usr/local/lib/python2.7/dist-packages/sshpubkeys/keys.py\", line 157, in hash_md5\n    fp_plain = hashlib.md5(self._decoded_key).hexdigest()\nTypeError: md5() argument 1 must be string or buffer, not None\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
	to retry, use: --limit @/work/ansible-beginner/main.retry

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1   
```

**Comment by greut** [comment]
@1605200517 hey, sorry that I didn't gave you any output on that. Indeed I have trouble creating the ssh key but didn't take the time to investigate any longer. Did you try asking for help on the ansible repository?

**Comment by 1605200517** [comment]
UPDATE.
I have tried to use Python debugger:

`ANSIBLE_ENABLE_TASK_DEBUGGER=True ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook main.yml -vvvv `

But then, I see that the file 

`/root/.ansible/tmp/ansible-tmp-1540197991.746526-125643635688315/AnsiballZ_cs_instance.py`

gets generated again as I run "redo" step in the debugger; where to place breakpoints then?

**Comment by 1605200517** [comment]
@greut for some reason, I can't see your recent comment and my update in this thread;

an issue on Ansible GitHub was deleted.

**Comment by 1605200517** [comment]
test

**Comment by 1605200517** [comment]
Now we have resolved it: one of the playbook files was missing variables like VM name.

**Comment by greut** [comment]
@1605200517 congrats!
